
from .intervaltree import Interval, IntervalTree


# def test_is_subset():
#     t1 = IntervalTree[int]()
#     t1.addi(1, 2)
#     t1.addi(3, 5)
#     t2 = IntervalTree[int]()
#     t2.addi(1, 2)
#     t2.addi(3, 4)
#     assert(t2 <= t1)
#     assert(not (t1 <= t2))
#     t3 = IntervalTree()
#     t4 = IntervalTree()
#     assert(t3 <= t4)


def test_intervaltree_add_contains():
    t1 = IntervalTree[int]()
    assert(Interval(1,0) not in t1)
    assert(Interval(1,1) not in t1)
    assert(Interval(1,2) not in t1)
    assert(Interval(1,3) not in t1)
    assert(Interval(1,4) not in t1)
    assert(Interval(1,5) not in t1)
    assert(Interval(2,0) not in t1)
    assert(Interval(2,1) not in t1)
    assert(Interval(2,2) not in t1)
    assert(Interval(2,3) not in t1)
    assert(Interval(2,4) not in t1)
    assert(Interval(2,5) not in t1)
    assert(Interval(3,0) not in t1)
    assert(Interval(3,1) not in t1)
    assert(Interval(3,2) not in t1)
    assert(Interval(3,3) not in t1)
    assert(Interval(3,4) not in t1)
    assert(Interval(3,5) not in t1)
    t1.addi(1, 2)
    assert(Interval(1,0) not in t1)
    assert(Interval(1,1) not in t1)
    assert(Interval(1,2) in t1)
    assert(Interval(1,3) not in t1)
    assert(Interval(1,4) not in t1)
    assert(Interval(1,5) not in t1)
    assert(Interval(2,0) not in t1)
    assert(Interval(2,1) not in t1)
    assert(Interval(2,2) not in t1)
    assert(Interval(2,3) not in t1)
    assert(Interval(2,4) not in t1)
    assert(Interval(2,5) not in t1)
    assert(Interval(3,0) not in t1)
    assert(Interval(3,1) not in t1)
    assert(Interval(3,2) not in t1)
    assert(Interval(3,3) not in t1)
    assert(Interval(3,4) not in t1)
    assert(Interval(3,5) not in t1)
    t1.addi(3, 4)
    assert(Interval(1,0) not in t1)
    assert(Interval(1,1) not in t1)
    assert(Interval(1,2) in t1)
    assert(Interval(1,3) not in t1)
    assert(Interval(1,4) not in t1)
    assert(Interval(1,5) not in t1)
    assert(Interval(2,0) not in t1)
    assert(Interval(2,1) not in t1)
    assert(Interval(2,2) not in t1)
    assert(Interval(2,3) not in t1)
    assert(Interval(2,4) not in t1)
    assert(Interval(2,5) not in t1)
    assert(Interval(3,0) not in t1)
    assert(Interval(3,1) not in t1)
    assert(Interval(3,2) not in t1)
    assert(Interval(3,3) not in t1)
    assert(Interval(3,4) in t1)
    assert(Interval(3,5) not in t1)

